<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXnkW2FV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXnkW2FV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXnkW2FV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXnkW2FV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXnkW2FV\App_KernelDevDebugContainer([
    'container.build_hash' => 'XnkW2FV',
    'container.build_id' => 'd6f2f65c',
    'container.build_time' => 1636389110,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXnkW2FV');
